"""empty message

Revision ID: 661ea6f9cd8b
Revises: 737f4b031257
Create Date: 2025-10-06 23:36:25.716845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '661ea6f9cd8b'
down_revision = '737f4b031257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pokemon_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['id'])
        batch_op.create_foreign_key(None, 'pokemon', ['pokemon_id'], ['id'])
        batch_op.drop_column('object_id')
        batch_op.drop_column('object_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_type', postgresql.ENUM('POKEMON', 'ITEM', name='favoritetype'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('item_id')
        batch_op.drop_column('pokemon_id')

    # ### end Alembic commands ###
