"""empty message

Revision ID: c9adec5be342
Revises: 7583948040fe
Create Date: 2025-09-28 22:07:31.468671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9adec5be342'
down_revision = '7583948040fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('atributes',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('ability',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('base_experience',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('generation',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('generation',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('base_experience',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ability',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('atributes',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
